from pydantic import BaseModel, Field

# ---------------------------------------------------------
# 1. BASE MODELS (Shared Fields)
# ---------------------------------------------------------
class BaseTask(BaseModel):
    """Fields common to ALL tasks and subtasks"""
    id: str  # Changed to str to prevent ID collisions!
    type: str
    title: str
    description: str
    acceptance_criteria: list[str]
    dependencies: list[str] # Also changed to str

class BasePlan(BaseModel):
    """Fields common to ALL plans"""
    scope_analysis: str = Field(description="Analyze the PO's requirement. What sub-systems need to be built? What are the hidden complexities?")
    technical_assumptions: list[str] = Field(description="List assumptions made about the tech stack or missing details.")

# ---------------------------------------------------------
# 2. SPECIFIC TASK MODELS
# ---------------------------------------------------------
class SubTask(BaseTask):
    """A leaf-level task — cannot have further subtasks."""
    
    def to_task(self, is_sufficiently_atomic: bool | None = None) -> "Task":
        return Task(
            **self.model_dump(),
            subtasks=None,
            is_sufficiently_atomic=is_sufficiently_atomic
        )

class Task(BaseTask):
    """A top-level task that might contain subtasks."""
    subtasks: list[SubTask] | None = None   # max 1 level, enforced by type
    
    is_sufficiently_atomic: bool | None = Field(default=None, exclude=True)

class InitialTaskList(BaseModel):
    """The initial list of tasks generated by the PM Agent, without any nesting."""
    tasks: list[SubTask]

# ---------------------------------------------------------
# 3. SPECIFIC PLAN MODELS
# ---------------------------------------------------------
class InitialPlan(BasePlan):
    """The first draft generated by the PM Agent (flat list of tasks)."""
    tasks: list[SubTask]

class Plan(BasePlan):
    """The final, refined plan containing nested/decomposed tasks."""
    tasks: list[Task]